swagger: '2.0'
info:
  description: Fuel Cost API
  version: 1.0.0
  title: Fuel Cost API
  contact:
    email: david@infinitycontracting.com
  license:
    name: MIT License
    url: http://opensource.org/licenses/MIT
host: "infinity-fuel-prices.herokuapp.com"
paths:
  /fuelcost:
    get:
      summary: calculates fuel cost, duty paid and delta today
      operationId: fuelcost
      produces:
      - application/json
      parameters:
      - name: date
        in: query
        description: date on which journey was made
        required: true
        type: string
        format: date
      - name: fuelType
        in: query
        description: Fuel type used
        required: true
        type: string
        enum: [ULSP, ULSD]
      - name: milesPerGallon
        in: query
        description: Vehicle fuel efficiency in miles per UK gallon
        required: true
        type: number
      - name: mileage
        in: query
        description: Distance travelled in miles
        required: true
        type: number
      responses:
        200:
          description: Fuel cost details
          schema:
            type: object
            example: {"fuelCost":3887,"dutyPaid":1264,"deltaToday":-22}
            items:
              $ref: '#/definitions/FuelCost'
        400:
          description: bad input parameter
definitions:
  FuelCost:
    type: object
    required:
    - fuelCost
    - dutyPaid
    - deltaToday
    properties:
      fuelCost:
        type: integer
        description: Total fuel cost in UK pence (£0.01)
        example: 1234
      dutyPaid:
        type: integer
        description: Total UK duty paid in UK pence (£0.01)
        example: 1234
      deltaToday:
        type: integer
        description: How much cheaper/more expensive would the journey have been today?
        example: -200
